import { 
  FileText, Zap, Camera, Video, Music, Code, Cloud, Database, 
  Server, Lock, Mail, MessageCircle, Share2, Download, Upload, 
  Edit, Trash2, Plus, Minus, Search, Filter, Settings, HelpCircle, 
  Users, UserPlus, Bell, Calendar, Clock, MapPin, Globe, Link, 
  Image, Film, Mic, Headphones, Book, Star, Heart, Flag, Award, 
  Briefcase, DollarSign, GraduationCap, Activity, Palette, 
  TrendingUp, FileCheck, Users2, Timer, Bookmark, Notebook, 
  BarChart, Receipt, Coins, Landmark, Handshake, Target, CreditCard,
  Lightbulb, Brain, PenTool, Layers, Grid, Type, Crop, Ruler, Eye, 
  Droplet, Moon, Smartphone, Monitor
} from 'lucide-react';

export const toolsConfig = [
  // 💼 Productivity & Business
  { id: 'invoice-forge', path: '/tools/invoice-forge', name: 'Invoice Forge', description: 'Create professional invoices instantly.', icon: 'filecheck', category: 'productivity' },
  { id: 'resume-rocket', path: '/tools/resume-rocket', name: 'Resume Rocket', description: 'Build ATS friendly resumes quickly.', icon: 'filetext', category: 'productivity' },
  { id: 'contract-craft', path: '/tools/contract-craft', name: 'Contract Craft', description: 'Generate legal contracts easily.', icon: 'filecheck', category: 'productivity' },
  { id: 'meet-mate', path: '/tools/meet-mate', name: 'Meet Mate', description: 'Schedule meetings effortlessly.', icon: 'calendar', category: 'productivity' },
  { id: 'focus-flow', path: '/tools/focus-flow', name: 'Focus Flow', description: 'Pomodoro timer for productivity.', icon: 'timer', category: 'productivity' },
  { id: 'link-vault', path: '/tools/link-vault', name: 'Link Vault', description: 'Save and organize important links.', icon: 'link', category: 'productivity' },
  { id: 'note-nest', path: '/tools/note-nest', name: 'Note Nest', description: 'Take notes with rich formatting.', icon: 'bookmark', category: 'productivity' },
  { id: 'standup-bot', path: '/tools/standup-bot', name: 'Standup Bot', description: 'Automate team standup meetings.', icon: 'users2', category: 'productivity' },
  
  // 💰 Finance & Budget
  { id: 'budget-buddy', path: '/tools/budget-buddy', name: 'Budget Buddy', description: 'Track your monthly expenses.', icon: 'dollarsign', category: 'finance' },
  { id: 'loan-lens', path: '/tools/loan-lens', name: 'Loan Lens', description: 'Calculate loan payments and interest.', icon: 'landmark', category: 'finance' },
  { id: 'coin-flip', path: '/tools/coin-flip', name: 'Coin Flip', description: 'Make decisions with coin toss.', icon: 'coins', category: 'finance' },
  { id: 'tax-tally', path: '/tools/tax-tally', name: 'Tax Tally', description: 'Calculate your tax returns.', icon: 'receipt', category: 'finance' },
  { id: 'split-ease', path: '/tools/split-ease', name: 'Split Ease', description: 'Split bills with friends.', icon: 'handshake', category: 'finance' },
  { id: 'net-worth-now', path: '/tools/net-worth-now', name: 'Net Worth Now', description: 'Calculate your net worth.', icon: 'trendingup', category: 'finance' },
  { id: 'freelance-fee', path: '/tools/freelance-fee', name: 'Freelance Fee', description: 'Calculate freelance rates.', icon: 'creditcard', category: 'finance' },
  { id: 'expense-snap', path: '/tools/expense-snap', name: 'Expense Snap', description: 'Scan and track receipts.', icon: 'camera', category: 'finance' },
  
  // 🎓 Education & Learning
  { id: 'flash-genius', path: '/tools/flash-genius', name: 'Flash Genius', description: 'Create digital flashcards.', icon: 'lightbulb', category: 'education' },
  { id: 'quiz-forge', path: '/tools/quiz-forge', name: 'Quiz Forge', description: 'Create interactive quizzes.', icon: 'brain', category: 'education' },
  { id: 'grade-grid', path: '/tools/grade-grid', name: 'Grade Grid', description: 'Calculate your GPA.', icon: 'barchart', category: 'education' },
  { id: 'study-sync', path: '/tools/study-sync', name: 'Study Sync', description: 'Collaborative study tool.', icon: 'users', category: 'education' },
  { id: 'cite-craft', path: '/tools/cite-craft', name: 'Cite Craft', description: 'Generate citations in APA/MLA.', icon: 'book', category: 'education' },
  { id: 'typing-trail', path: '/tools/typing-trail', name: 'Typing Trail', description: 'Improve typing speed.', icon: 'type', category: 'education' },
  { id: 'mind-map-maker', path: '/tools/mind-map-maker', name: 'Mind Map Maker', description: 'Create visual mind maps.', icon: 'grid', category: 'education' },
  { id: 'countdown-class', path: '/tools/countdown-class', name: 'Countdown Class', description: 'Track exam deadlines.', icon: 'clock', category: 'education' },
  
  // 🏥 Health & Lifestyle
  { id: 'body-check', path: '/tools/body-check', name: 'Body Check', description: 'BMI and health calculator.', icon: 'activity', category: 'health' },
  { id: 'meal-map', path: '/tools/meal-map', name: 'Meal Map', description: 'Plan your weekly meals.', icon: 'droplet', category: 'health' },
  { id: 'hydro-track', path: '/tools/hydro-track', name: 'Hydro Track', description: 'Track water intake.', icon: 'droplet', category: 'health' },
  { id: 'fit-forge', path: '/tools/fit-forge', name: 'Fit Forge', description: 'Create workout plans.', icon: 'activity', category: 'health' },
  { id: 'med-minder', path: '/tools/med-minder', name: 'Med Minder', description: 'Medication reminders.', icon: 'bell', category: 'health' },
  { id: 'sleep-score', path: '/tools/sleep-score', name: 'Sleep Score', description: 'Track sleep quality.', icon: 'moon', category: 'health' },
  { id: 'mood-log', path: '/tools/mood-log', name: 'Mood Log', description: 'Journal your emotions.', icon: 'heart', category: 'health' },
  { id: 'step-streak', path: '/tools/step-streak', name: 'Step Streak', description: 'Track daily steps.', icon: 'activity', category: 'health' },
  
  // 🎨 Design & Developer Tools
  { id: 'palette-pickr', path: '/tools/palette-pickr', name: 'Palette Pickr', description: 'Generate color palettes.', icon: 'palette', category: 'design' },
  { id: 'gradient-guru', path: '/tools/gradient-guru', name: 'Gradient Guru', description: 'Create beautiful gradients.', icon: 'layers', category: 'design' },
  { id: 'qr-quick', path: '/tools/qr-quick', name: 'QR Quick', description: 'Generate QR codes instantly.', icon: 'smartphone', category: 'design' },
  { id: 'shadow-smith', path: '/tools/shadow-smith', name: 'Shadow Smith', description: 'Create CSS shadows.', icon: 'crop', category: 'design' },
  { id: 'font-fusion', path: '/tools/font-fusion', name: 'Font Fusion', description: 'Combine Google Fonts.', icon: 'type', category: 'design' },
  { id: 'icon-snap', path: '/tools/icon-snap', name: 'Icon Snap', description: 'Browse icon collections.', icon: 'grid', category: 'design' },
  { id: 'contrast-check', path: '/tools/contrast-check', name: 'Contrast Check', description: 'Check color contrast.', icon: 'eye', category: 'design' },
  { id: 'screen-sizer', path: '/tools/screen-sizer', name: 'Screen Sizer', description: 'Test responsive designs.', icon: 'monitor', category: 'design' },
];

export const getIconByName = (iconName) => {
  const icons = {
    filetext: FileText,
    zap: Zap,
    camera: Camera,
    video: Video,
    music: Music,
    code: Code,
    cloud: Cloud,
    database: Database,
    server: Server,
    lock: Lock,
    mail: Mail,
    messagecircle: MessageCircle,
    share2: Share2,
    download: Download,
    upload: Upload,
    edit: Edit,
    trash2: Trash2,
    plus: Plus,
    minus: Minus,
    search: Search,
    filter: Filter,
    settings: Settings,
    helpcircle: HelpCircle,
    users: Users,
    userplus: UserPlus,
    bell: Bell,
    calendar: Calendar,
    clock: Clock,
    mappin: MapPin,
    globe: Globe,
    link: Link,
    image: Image,
    film: Film,
    mic: Mic,
    headphones: Headphones,
    book: Book,
    star: Star,
    heart: Heart,
    flag: Flag,
    award: Award,
    briefcase: Briefcase,
    dollarsign: DollarSign,
    graduationcap: GraduationCap,
    activity: Activity,
    palette: Palette,
    trendingup: TrendingUp,
    filecheck: FileCheck,
    users2: Users2,
    timer: Timer,
    bookmark: Bookmark,
    notebook: Notebook,
    barchart: BarChart,
    receipt: Receipt,
    coins: Coins,
    landmark: Landmark,
    handshake: Handshake,
    target: Target,
    creditcard: CreditCard,
    lightbulb: Lightbulb,
    brain: Brain,
    pentool: PenTool,
    layers: Layers,
    grid: Grid,
    type: Type,
    crop: Crop,
    ruler: Ruler,
    eye: Eye,
    droplet: Droplet,
    moon: Moon,
    smartphone: Smartphone,
    monitor: Monitor,
  };
  return icons[iconName.toLowerCase()] || Zap;
};